JuliaDataScience/JuliaDataScience

- CITATION.cff
Made using this: https://citation-file-format.github.io/cff-initializer-javascript/
Could not find @lazarusA ORCID, went to some of his publications at Google Scholar and in a paper his coauthors had ORCID and he did not, so I think that he has not one.
> Created CITATION.cff

- contents/julia_101.md
- contents/preface.md
- contents/why_julia.md
Fix #42.
It was caused by using wrong syntax. Only citations should be put inside square brackets not references to figures, tables and sections.
> Fix section references

- contents/index.md
- src/JDS.jl
I did a reasonably big refactor of Books.jl again (https://github.com/rikhuijzer/Books.jl/pull/170).
Now, some small bugs are fixed, the package is more robust and Books.jl is about 10% more quick in building the HTML files for JuliaDataScience.
In this PR, I enable the `fail_on_error` option for `Books.build_all`. With this option, the build will fail on missing cross-references.
> Enable verification of crossrefs

- contents/julia_101.md
Since the splatting operator is mostly used in "collections" (such as arrays, vectors and tuples), I've included it in the bottom of the "Native Data Structures" section of "Julia 101" chapter.
Closes #31.
> Added splatting operator to Julia 101

- contents/julia_101.md
Thanks to https://github.com/rikhuijzer/Books.jl/pull/180, the indentation is now fixed.
I've disallowed blocks without a newline before the block since that is more in line with how it works for non-indented code blocks. Therefore, this PR adds a newline before the two indented blocks which didn't have a newline in front.
> Fix not evaluating code blocks

- .github/FUNDING.yml
I think this implements the funding button with the GitHub Sponsors on our repo. Like the pic above:
The documentation can be viewed here: https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository
Please check if I am doing this right.
> added funding button

- Project.toml
I manually compared the local page to `https://juliadatascience.io/load_save` and didn't see any problems.
We should, probably, add tests to automate this manual skimming, but I currently don't think it's worth the time. We just need to keep in mind that we add a test whenever we get issue reports in the future about wrong outputs.
> Set CSV.jl compat to 0.9

- contents/appendix.md
- contents/index.md
- metadata.yml
Closes #113.
@storopoli, I couldn't figure out to add the roadmap nicely to the PDF. Instead, there is now clear message at the bottom of every second page which redirects users to the homepage:
Also, each generated PDF now contains the date and time of the build.
> Add roadmap

- contents/dataframes_performance.md
> Added Performance section to DataFrames chapter

- config.toml
- contents/dataframes_load_save.md
- contents/julia_basics.md
- contents/notation.md
- pandoc/references.bib
- src/JDS.jl
- src/df.jl
- src/environment.jl
- src/showcode_additions.jl
@lazarusA, in response to using Plots and Makie at the same time. I think that the most future proof solution is to use
```
@reexport begin
using Plots:
plot,
[...]
using Makie:
density,
[...]
end # @reexport
```
The rationale is added to the notation section and can also be read in the [JuMP Style Guide](https://jump.dev/JuMP.jl/stable/developers/style/#using-vs.-import).
As a proof-of-concept, I've implemented it for `DataFrames.jl` and `XLSX.jl` already.
This pattern is also used at other places. For example, in [`JETTest.jl`](https://github.com/aviatesk/JETTest.jl/blob/master/src/JETTest.jl).
> Document using versus import

- .github/workflows/CI.yml
- .github/workflows/Format.yml
- contents/data_vis_makie_animations.md
- contents/data_vis_makie_attributes.md
- contents/data_vis_makie_colors.md
- contents/data_vis_makie_glmakie.md
- contents/data_vis_makie_layouts.md
- contents/dataframes_performance.md
- contents/preface.md
- contents/stats.md
- contents/stats_distributions.md
- format/Project.toml
- format/src/FormatJDS.jl
- format/src/juliaformatter.jl
- format/src/whitespace.jl
- src/JDS.jl
- src/bezier.jl
- src/front-cover.jl
- src/makie.jl
- src/plots.jl
- src/stats.jl
Add a simple trailing whitespace check.
For some reason, CI in #124 is broken. So, that's why this is a new PR for the same thing.
To locally remove all whitespace, use:
```
$ julia --project=format
julia> using FormatJDS
julia> remove_trailing_whitespace()
```
EDIT: I've tried only starting `CI` if `Format` succeeds to save some build minutes. Unfortunately, that should be done via `workflow_run` and that appears to be a bit weird. There even exist Actions to workaround missing functionality (for example, https://github.com/ahmadnassri/action-workflow-run-wait).
> Fix trailing whitespace

- contents/index.md
- src/JDS.jl
- src/front-cover.jl
As mentioned in b5dcea4befb5a2910f8b2eb8772ca0ef629aeb90, 506e24078ea60e95b13a030ee6f5feabbba05523 and #123. This PR shows the cover on the front page. The image isn't centered unfortunately. It's a bug in Books.jl: https://github.com/rikhuijzer/Books.jl/issues/217. I'll fix that.
This is the full size image. To avoid the 1.4 MB image to slow down the homepage loading, I've set `loading="lazy"` (more info at https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading).
<br>
<br>
> Show cover on front page

- contents/dataframes_performance.md
I would say that it's up to the reader to decide when to use the pipe and when not. There are cases where the pipe indeed makes more sense for `CSV.File`, but there are also cases when not. Therefore, calling it "more preferred idiomatic" is a bit too strong.
> Change wording to be less strong

- Project.toml
- contents/index.md
- contents/preface.md
- src/JDS.jl
- src/cover.jl
- src/front-cover.jl
This PR add code to generate the full cover. See https://github.com/JuliaDataScience/JuliaDataScience/issues/17#issuecomment-927185934 for more information about the dimensions.
I don't consider the cover done and perfect now. It is meant as a place where we can start discussing the appearance.
**EDIT:** This wasn't working in Amazon. It was turned into 
So, instead using the Amazon cover editor:
which is turned into
> Add full cover

- contents/dataframes_performance.md
This PR modifies the performance section of the `DataFrames.jl` chapter.
Since version 1.3 `DataFrames.jl` will support an *in-place* `leftjoin!`.
Thanks for the advice @bkamins.
Closes #149
> Added leftjoin! to performance section

- contents/why_julia.md
Hello!
This PR fixes a small typing error in animal types.
`Box` should be a `Fox`.
> Typo: Box -> Fox

- src/ci.jl
@lazarusA is this okay? Pirsch offers the same functionality as Fathom and is also very private by design, but they do it for a much lower price. If you agree, I plan to remove Fathom in a month. For now, they can run side by side.
> Add Pirsch analytics

- .github/workflows/CI.yml
Let's stick to stable (or at least tagged) versions of Books.jl
> Use stable Books.jl version instead of main

- contents/data_vis_makie_colors.md
Hi, @rikhuijzer .
I found a small typo in data_vis_makie_colors.md and fixed it.
`trough` should be `through`.
> Fix typo in data_vis_makie_colors.md

- contents/julia_basics.md
The pkg name is `Downloads` not `Download`.
> Update julia_basics.md fix typo in Downloads

- contents/julia_basics.md
while the syntax of the commands `startswith` and `endswith` was corrected in PR #214, the surrounding text wasn't adapted to that change as well. This is done in this PR. To simplify that, also the command `occursin` was changed to `contains` which has the same syntax as `startswith` and `endwith` (and internally calls `occursin`).
> improve PR #214

- contents/index.md
Someone in our university said that she would immediately click on the PDF link if she would look at our site. With Pirsch, we can luckily also add a onclick event to those links to get a better idea of how many people prefer to look at the PDF instead of HTML.
> Track links on homepage

- contents/index.md
All events shop up as "Link Clicked" which is not so helpful. This PR should fix that.
> Avoid having all click events look the same

- contents/julia_basics.md
Fixes #234.
This was caused by a collision of the output filenames of the blocks again. I've added some comments to fix that problem.
EDIT: Also, I've simplified the text a bit.
> Update rand text

- CITATION.cff
The only place that I could add the ISBN was in the preferred citation area (https://github.com/citation-file-format/citation-file-format/blob/main/examples/1.2.0/pass/key-complete/CITATION.cff), so that's why I added that.
I have no idea what the precise effects are on Zotero but I guess it is an improvement.
> Add ISBN to CITATION.cff

- .github/workflows/CI.yml
```bash
cp -r ~/jds/pt _build/pt
```
copies the folder `pt/` to `_build/pt/pt`
We need to have just:
```bash
cp -r ~/jds/pt _build
```
> Fix additional subfolder created by CI.yml in Portuguese Version

- contents/julia_basics.md
> Fix `scob` when Float32 is explictly demonstrated

- .devcontainer/Dockerfile
- .devcontainer/run.sh
- .github/workflows/CI.yml
- Project.toml
- src/JDS.jl
- src/ci.jl
- src/makie.jl
I'm having a bit of trouble running this locally (NixOS nor Docker manage to run all blocks :sweat_smile:), but if CI passes then all should be good. Unless there are objections, I'm planning to send an updated PDF to Amazon because syntax highlighting is disabled for output blocks now which looks better.
Version 2 closes about 6 long-standing issues. Most noteworthy:
- Syntax highlighting is disabled for output blocks in both HTML and PDF. This makes the books and websites look much cleaner.
- The output is printed via `ProgressMeter.jl` instead of a dump to the console. This avoids a lot of scrolling when using `gen`.
- All code is now always evaluated in `Main`. There used to be two ways to do it, but having one is much simpler and therefore better.
- Yggdrasil is now used for Tectonic …
> Switch to Books v2

- contents/julia_basics.md
`1:length` depends on the endpoints of the indexing, so is unsafe for OffsetArrays. `eachindex` is more generic and clear about the intent of the operation.
> Use `eachindex` instead of `1:length`

- src/cheatSheet_cairo.jl
Some suggested changes to the CairoMakie cheatsheet, some for consistency and some to make it easier to understand what the function actually does (I think that is the main use of this figure: once the purpose of a plotting function is clear, the user can always check the documentation for the different ways to call the function). The biggest change is for `linesegments`: it now uses the `linesegments(x, y)` signature with the same data as the previous plots, to help understanding what's going on.
Full list of changes:
* change range of first plots to have even number of points (for linesegments)
* change linesegments to use same data as previous plots
* uniformize parameter names in plot titles
* use variable heights in crossbar
* fix title of violin plot
* more explicit title for mesh
> cheatSheet_cairo.jl improvements

- contents/dataframes.md
The original wording can be confusing to a naïve reader.  For example, the phrase "Columns are usually of the same data type" sounds like it is saying that columns have a data type and this type is usually the same for all columns.  I think it is clearer to state that all the elements in a given column share the same data type.
> Edit for clarity

- .github/dependabot.yml
- .github/workflows/CI.yml
- .github/workflows/Format.yml
Also updates some old actions that were giving warnings on CI. Changes the runner machines to all be ubuntu-latest which is the latest LTS ubuntu.
> ci: add dependabot

- .github/workflows/CI.yml
I don't know when GitHub will give us runners with more than 2 threads, so this is future-proofing...
> ci: set `JULIA_NUM_THREADS` to `"auto"` by default

- .github/workflows/CI.yml
In response to
> Why not pin to 1.10 since that is the new LTS?
https://github.com/JuliaDataScience/JuliaDataScience/pull/348#issuecomment-2405773369
> Set Julia version to 1.10
