contents/preface.md, contents/why_julia.md
Also some changes to the why Julia text
=> Add software engineering to preface

.github/workflows/CI.yml, Project.toml, contents/appendix.md, contents/plots_overview.md, contents/preface.md, src/JDS.jl
Changes after https://github.com/rikhuijzer/Books.jl/pull/131.
=> Update code blocks after update of Books

README.md
So far, we're already complying with this style, but I think it would be good to mention it. It's a pretty nice style if you ask me.
Merge if you agree! Thanks
=> Add code style blue

contents/julia_101.md, contents/preface.md, contents/why_julia.md
The CI should now pass thanks to https://github.com/rikhuijzer/Books.jl/pull/147.
=> Fix broken PDF build on Julia 101 branch

README.md
@storopoli The hitcounter takes 30 seconds to load and is, I think therefore, not visible
Mainly, I'm also making this change to verify that Books.jl is now fixed.
=> (Temporary) Remove hitcounter

Project.toml, contents/index.md, metadata.yml
Closes #32.
@lazarusA could you check whether I've spelled your name correctly and merge this PR?
=> Add Alonso as coauthor

contents/julia_101.md, contents/preface.md, contents/why_julia.md
=> Fix some grammar mistakes

contents/julia_101.md
=> small typo fix

config.toml, contents/appendix.md, contents/notation.md, contents/project_management.md
Moves our discussion from #23 into the book/into git.
=> Add section on notation

contents/dataVis.md, src/makie.jl
=> Add makie quote and more blue code compliances.

contents/why_julia.md
Proposed simplification of the form of a question.
=> Simplify a sentence

contents/preface.md
=> Fix typos in preface

contents/julia_101.md, contents/why_julia.md
Super quick PR. Minor changes.
Fixes #70
=> fixed spelling for use case and mix and match

.github/workflows/CI.yml
=> added color terminal output to CI

contents/data_vis_makie.md
this fixes issue https://github.com/JuliaDataScience/JuliaDataScience/issues/82
Closes #82.
=> Fix broken link to makie docs

contents/why_julia.md
I've tried to keep the PR a bit short to avoid huge discussions. Let me know if you have doubts about one of my changes!
=> Review why Julia

contents/preface.md
I was thinking yesterday about Statistical Rethinking and remembered that I could easily remember **why** McElreath wrote the book. He wished that he was taught statistics like he did in the book.
For our preface, I now also added a bit more personal viewpoint.
Please both of you check whether you agree with my opinion.
=> Add more personal story to preface

config.toml, contents/dataframes_indexing.md, contents/julia_basics.md, contents/why_julia.md
I've renamed it to Julia Basics because my brain was thinking "what does 101 mean?" all the time. I've heard the term before, but I can't seem to remember it.
=> Review Julia basics up until arrays

README.md, src/JDS.jl
Switching to another analytics provider has two benefits:
1. We are GDPR compliant again without having to add a consent button.
2. Less people block Fathom analytics than Google analytics, so the information should be slightly more reliable.
Fathom analytics costs $14/month which I'll pay for now :+1:.
=> Switch to Fathom analytics

contents/index.md
Since Friday, about 130 unique people have looked at the front page. However, the front page doesn't indicate that the book is unfinished which, I expect, can be very frustrating for visitors when they click a link in the menu without content
=> Add work in progress mention on homepage

config.toml, contents/index.md
This PR:
1. removes the empty `files/` folder
2. adds @lazarusA to the bibtext citation key
3. removes first names from the APA citation
=> removed empty files folder and changed bibtex citation

contents/data_vis_makie_cairo.md, src/JDS.jl, src/makie.jl
In response to https://github.com/rikhuijzer/Books.jl/issues/192. I've set the width to 70% now for simple images.
Note that this will change the width in both the HTML and PDF output. This makes it easier when developing with HTML to imagine how it is going to look in the PDF.
=> Resize simple image

contents/data_vis_makie_attributes.md, contents/index.md, contents/stats_vis.md, pandoc/references.bib, src/JDS.jl, src/stats.jl
Closes #112 
OBS: I had to name a section on Makie chapter because I need to reference it in this chapter (cc @lazarusA)
=> [Statistics] Final Section on Statistical Visualizations

contents/stats_vis.md
Now it is:
1. Histograms
2. Box Plots
3. Density Plots
=> [Statistics Chapter] Changed order of statistical visualizations

contents/index.md, src/JDS.jl, src/ci.jl
Via (what looks like) the awesome https://www.staticforms.xyz/ project.
---
---
If you try to fill in something that isn't an email address, then the form shows "Please enter an email address." (Firefox).
If you fill in a valid email address, then you end up at https://juliadatascience.io/thanks:
---
---
Submissions to this form end up in my mailbox. If someone else wants to offer their mailbox then that's fine too (even appreciated :stuck_out_tongue_closed_eyes:)
=> Add mail submit form

src/front-cover.jl
I've cleaned it up.
What needs to be done:
1. The two pipes from 2nd and 3rd row need to have a little padding to the left (maybe 3-4 spaces)
I also renamed the axis to something like ax12 for `Axis(fig[2,3])` which for me is better than the serial ax1 to ax19 or something like that.
I also used `GLMakie`, the original code was using `CairoMakie`. Maybe we need to change that back.
Here is the current book cover from this PR
=> Book Cover

metadata.yml
Thanks to https://github.com/rikhuijzer/Books.jl/pull/226.
=> Configure titlepage

contents/dataframes.md, contents/index.md, contents/julia_basics.md, contents/preface.md, contents/why_julia.md
re #137 
I made some minor copy edits to the first three chapters, hope I haven't disturbed the book's syntax.
I'll admit that a fair few of these are likely matters of personal taste :) Sometimes it's just an attempt at rephrasing to make the sentences flow a bit more smoothly to my ears.
=> Some proof-reading: chapters 1 to 3

src/front-cover.jl
this should fix some alignment issues regarding the pipes. Additionally, I did a print for the previous one and the lack of grid lines makes the whole cover a little bit dull.
=> Fix pipe alignment in front cover

src/front-cover.jl
this should fix the size ratio and rm the empty axis.
=> Fixed ratio front cover

contents/julia_basics.md
I combined some time here and there to read through the section.
=> Rewrite Julia Basics

metadata.yml
Fixes the error introduced by me in https://github.com/JuliaDataScience/JuliaDataScience/commit/0d953ff0767361fc748959416f1c8c5bde7e815a.
My bad. Tested locally this time.
=> Fix metadata

contents/data_vis_makie_attributes.md, contents/data_vis_makie_colors.md, contents/data_vis_makie_latex.md, contents/data_vis_makie_themes.md, src/makie.jl
This should be a clear branch, with clean commits. 
- Small descriptions for data input where necessary
- Main change: Figure sizes, so that they are more consistent in the pdf version.
- TODO: GLMakie, still needs more descriptions regarding figure building. Will do in another PR.
=> Better default figure sizes for PDF

contents/why_julia.md
Hello!
Probably there is a typo in the `naive_trouble` function.
The second and third conditions are identical (both, A and B are chickens):
```
function naive_trouble(A::Animal, B::Animal)
if A isa Fox && B isa Chicken
return true
elseif A isa Chicken && B isa Chicken
return true
elseif A isa Chicken && B isa Chicken
return false
end
end
```
I assume that in the second conditions B should be a Fox, isn't it?
```
function naive_trouble(A::Animal, B::Animal)
if A isa Fox && B isa Chicken
return true
elseif A isa Chicken && B isa Fox
return true
elseif A isa Chicken && B isa Chicken
return false
end
en
```
With kind regards,
Vladimir
=> Typo in `naive_trouble`: chicken & fox

contents/data_vis_makie.md
let's hope this one is also include in the next release... if not. Then version.
=> how to display plots with CairoMakie

contents/julia_basics.md
Related to https://github.com/JuliaDataScience/JuliaDataScience/pull/200#issuecomment-959241728.
=> Add section on development environments

README.md, src/ci.jl
This will also slightly speed up page loading speed. Unless any of you disagrees, I'll remove Fathom and its data in a few days.
=> Remove Fathom analytics

contents/dataframes.md
Hello, I'm Nadia. I'm translating your book to portuguese, with @storopoli help.
I think this should be were, not where.
=> typo fix dataframes

contents/julia_basics.md
=> Julia Basics: improvements and suggestions

contents/preface.md
=> Preface: improvements and suggestions

contents/julia_basics.md
=> Fix Windows path typo

contents/dataframes_indexing.md
@Mo-Gul, well spotted.
Can you double check whether this fix is correct?
- Closes #227
=> Remove anonymous

contents/data_vis_makie.md, contents/data_vis_makie_attributes.md, contents/data_vis_makie_colors.md, contents/data_vis_makie_glmakie.md, contents/data_vis_makie_latex.md, contents/data_vis_makie_layouts.md, contents/data_vis_makie_themes.md, contents/stats_vis.md
As always, feel free to cherry-pick stuff and/or move parts to separate issues in case you don't want to solve this now.
=> Improve Makie chapter

contents/why_julia.md
This should make that section a lot clearer
=> Use `@code_llvm` to explain performance

.github/workflows/CI.yml
Also caches `JULIA_DEPOT/packages` so should be slightly faster
=> Switch to julia-actions/cache

.github/workflows/CI.yml, contents/index.md
This PR adds `JuliaDataScience/JuliaDataScience-PT` as a simple HTML button to the `index.md`
=> Add Portugese translation

contents/index.md
I've asked @findmyway and he said we can add the link
=> Add link to Chinese version

contents/index.md
=> Remove email signup

contents/data_vis_makie_colors.md, contents/data_vis_makie_glmakie.md, src/makie.jl
some clean up, plus this should also close https://github.com/JuliaDataScience/JuliaDataScience/issues/263 by means of using `aligmode`, the previous approach is no longer available, breaking change.
=> Revision makie chapter

config.toml, contents/data_vis_makie_recipe.md, src/JDS.jl
this adds a new section to the book, so I would say that is a breaking change. On the other hand I believe that is necessary to continue adding new content. Please take a look and suggest changes, specially for the DataFrames bit. 
This also addresses https://github.com/JuliaDataScience/JuliaDataScience/issues/266 very little, but some 😄 .
=> simple recipe for a DataFrame

contents/data_vis_makie_recipe.md
this adds options to the recipe in order to later on call `axislegend` and `Colorbar`.
=> adding legend and colorbar options to recipe

config.toml, contents/data_vis_makie.md, contents/dataframes.md, contents/dataframes_load_save.md, contents/dataframes_select.md, contents/julia_basics.md, contents/preface.md, contents/project_management.md, contents/why_julia.md
* Closes #192.
* Closes #279.
* Closes #265.
* Closes #266.
* Closes #267.
=> 2022 Updates

contents/data_vis_makie.md, contents/data_vis_makie_latex.md, contents/data_vis_makie_recipe.md, contents/data_vis_makie_themes.md, contents/dataframesmeta.md, contents/dataframesmeta_macros.md, contents/dataframesmeta_select.md, contents/dataframesmeta_subset.md
=> add some text connectors and updated several outdated links.

contents/dataframes_performance.md
Fix extra backtick in DataFrames performance section
=> Fix extra backtick

contents/data_vis_aog_stats.md, contents/data_vis_makie_layouts.md, contents/dataframesmeta_subset.md
Just fixed a few typos I've found while reading.
=> Fix a few typos

src/cheatSheet_glmakie.jl
=> fix: GLMakie cheatsheet rich text!

.github/workflows/CI.yml
Fixes https://github.com/JuliaDataScience/JuliaDataScience/issues/321.
I'm still debugging so feel free to unsubscribe.
=> Provide PDF artifact in PR

.devcontainer/Dockerfile
This fix might not need a retouch in the future.
=> fix(docker): update Dockefile to julia:latest

.github/workflows/CI.yml
This is not a good day I'm having. So much noise. This is the last one.
=> Reduce scope
